# Generated by Django 4.2.16 on 2024-11-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_input_difymodel_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="difymodel",
            name="conversation_id",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
