# Generated by Django 4.2.16 on 2024-11-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_difymodel_conversation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="difymodel",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
