# Generated by Django 4.2.16 on 2024-11-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_difymodel_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="difymodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
